services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
  - NODE_ENV=test
  - PORT=8080
  - DB_HOST=10.25.128.3
  - DB_PORT=3306
  - DB_USER=root
  - DB_PASSWORD=yourpassword
  - DB_NAME=testdb
    restart: always
    ports:
      - "80:8080"
    command: ["node", "index.js"]
